# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hyhhhhhh/citest
    environment:
      - GOPATH: /go
    steps:
      - checkout
      - run: 
         name: The First Step
         command: |
           echo 'Hello World!'
           uname -a 
           go version
           go test -race -coverprofile=coverage.txt -covermode=atomic ./...
           ls
      - run: bash <(curl -s https://codecov.io/bash)
